name: Build Project
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - github_action

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation depends
        run: |
          echo "Preparing environment..."
          sudo apt-get update
          sudo apt-get install -y python2-dev python2.7 python-dev-is-python3 python3 python3.9 git build-essential swig libnode-dev cmake libjson-c-dev libc6 libgcc1 libstdc++6 libgtest-dev pkg-config cmake-data
          echo "Environment setup complete."
      - name: Build project
        run: |
          Project_HOME_PATH=$PWD
          ls_files=$(ls -a ../)
          echo  "===== files: $ls_files ========= $PWD =============="
          mkdir build && cd build
          cmake "$Project_HOME_PATH"  && make -j8 && cpack -G DEB
          echo  "======== Build complete ====== $PWD =============="

  upload:
    needs: build # 声明 upload 作业依赖于 build 作业
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: My Artifact
          path: ./build/*.deb

