name: Build wiringX
on: 
  workflow_dispatch:
      pull_request:
      push:
        branches:
          - github_action

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation depends
      uses: actions/checkout@v4
      run: |
        echo "to prepare the env ..."
        sudo apt-get update
        echo "== install python env =="
        sudo apt-get install -y python2-dev python2.7 python-dev-is-python3 python3 python3.9
        sudo apt-get install -y git build-essential swig  libnode-dev  cmake libjson-c-dev libc6 libgcc1 libstdc++6   libgtest-dev pkg-config cmake-data
        echo "env ok ..."

    - name: Build
      run: |
      echo  "============== $PWD =============="
        # cd wiringX
        # mkdir build
        # cd build
        # cmake ..
        # make -j8
        # cpack -G DEB
        # echo  "============== $PWD =============="
    # - name : Upload artifact
    #   uses: actions/checkout@v4
    #   with:
    #     name: ${{ github.event.repository.name }}
    #     path: |
    #       ${{ env.artifacts_path }}/*.deb
